#+title: VOFA+ Documentation
#+author: Hanbin Zheng

* I. Overview

This telemetry suite utilizes the ARM Cortex-M background DAP (Debug Access Port) via RTT (Real-Time Transfer) to stream high-frequency visualization packets without consuming hardware UART peripherals or requiring extra USB-TTL wiring.

We divide the RTT upstream pipes into two dedicated channels:

We use the RTT upstream channel 1 to pipes float packets (via FireWater format) to TCP port ~9001~.

* II. API Reference

*** 1. ~vofa_init()~
Initializes and binds a static 2048-byte RAM ring buffer to RTT Up-Buffer Channel 1.

Return: ~VOFA_SUCCESS (0)~ on success, ~VOFA_FAILURE (-1)~ on failure.

*** 2. ~vofa_send(...)~
A reflective macro that accepts any number of arguments. Under the wireless Daplink, the transmission density should be less than 1000 float / s. For example, if you transmit 2 float numbers a time, the sampling frequency should be no more than 500 hz.

* III. Quick Start & Usage Example
To stream telemetry, call ~vofa_init()~ once during the board's startup phase, and feed variables to ~vofa_send(...)~ inside your control loop:

#+begin_src c
#include "bsp_dwt.h"
#include "vofa.h"

int main(void)
{
        dwt_init(MCU_MAIN_FREQ);
	vofa_init();

	float target = 0.0f;
	float actual = 0.0f;
	float time_ticks = 0.0f;

	while (1) {
		target = 100.0f * __builtin_sinf(time_ticks);
                actual += (target - actual) * 0.1f;
                time_ticks += 0.05f;

                vofa_send(target, actual);
                dwt_delay_ms(10);
	}
}
#+end_src

Low-Level Hex Stream Verification
If you suspect transmission errors, you can bypass VOFA+ and inspect the raw binary stream directly from your Mac terminal using a Netcat pipeline paired with a hex dumper:

#+begin_src bash
nc localhost 9001
#+end_src

You should observe contiguous float numbers in the format:


#+begin_src text
float1,float2,float3,float4.....
#+end_src

#+begin_src text
32.117599,61.286533
7.695588,42.959796
#+end_src

* IV. VOFA+ Upper Monitor Configuration

Learning Materials:
- VOFA+ Official Docs: [[https://www.vofa.plus/docs/learning][Documentation]]
- Supplements: [[https://b23.tv/q44mjxD][Bilibili Tutorial]]

Open your VOFA+ software and follow these configurations to map the binary network stream to the grapher canvas:

*** 1. Protocols & Connections (Left Sidebar)

Data Interface: ~TCP Client~

Data Engine: ~FireWater~

Server IP: ~127.0.0.1~ (localhost)

Server Port: ~9001~ (mapped to RTT Channel 1)

*** 2. Graphic Layout

Drag the Waveform control widget onto your main canvas grid.

Right-click the Waveform widget, go to Settings. Bind *X-axis* to *Timeline* and *Y-axis* to *All*.

Click the Connect (Play) button in the left sidebar above the TCP Client connector.
